name: hedgedoc
services:
  database:
    image: postgres:latest
    restart: always
    container_name: hedgedoc_postgres
    environment:
      POSTGRES_USER: hedgedoc
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret_user_password}
      POSTGRES_DB: hedgedoc
    env_file:
      - .env
    volumes:
      - hedgedoc_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U hedgedoc"]
      interval: 30s
      timeout: 10s
      retries: 5

  panel:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:latest
    restart: always
    container_name: hedgedoc_panel
    ports:
      - 3000:3000
    environment:
      CMD_DB_URL: postgres://hedgedoc:${POSTGRES_PASSWORD:-secret_user_password}@database:5432/hedgedoc
      CMD_DOMAIN: ${HEDGEDOC_DOMAIN:-localhost}
      CMD_PROTOCOL_USESSL: true
      CMD_ALLOW_ORIGIN: ${HEDGEDOC_ALLOW_ORIGIN:-["https://localhost"]}
    env_file:
      - .env
    volumes:
      - hedgedoc_uploads:/hedgedoc/public/uploads
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hedgedoc_database:
  hedgedoc_uploads:
