services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - nginx

volumes:
  data:
  letsencrypt:

networks:
  nginx:
    external: true
