services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: secret_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
    networks:
      - phpmyadmin

volumes:
  mysql_data:

networks:
  phpmyadmin:
    driver: bridge
