version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    expose:
      - "9443"
    ports:
      - 9443:9443
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
