x-common:
  database: &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "secret"
    MYSQL_ROOT_PASSWORD: "secret_root_password"
  panel: &panel-environment
    APP_URL: "http://localhost"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail: &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    restart: always
    networks:
      - pterodactyl
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "pterodactyl_database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
    networks:
      - pterodactyl
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pterodactyl
    volumes:
      - "pterodactyl_var:/app/var"
      - "pterodactyl_nginx:/etc/nginx/http.d/"
      - "pterodactyl_logs:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    ports:
      - "8080:8080"
      - "2022:2022"
    networks:
      - pterodactyl
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "pterodactyl_wings_config:/etc/pterodactyl/"
      - "pterodactyl_wings_logs:/var/log/pterodactyl/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      #- "/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"

volumes:
  pterodactyl_database:
  pterodactyl_var:
  pterodactyl_nginx:
  pterodactyl_logs:
  pterodactyl_wings_config:
  pterodactyl_wings_logs:

networks:
  pterodactyl:
    driver: bridge
