services:
  database:
    image: mysql:8.0
    container_name: pteroca_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: pteroca
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - pteroca_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    env_file:
      - .env
    networks:
      - pteroca

  webapp:
    build:
      context: .
      args:
        APP_ENV: prod
    container_name: pteroca_web
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://user:password@database:3306/pteroca?serverVersion=8.0}
      APP_ENV: prod
      CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - pteroca_app_var:/app/var
      - pteroca_app_uploads:/app/public/uploads
      - .env:/app/.env
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    command: >
      sh -c "
        echo 'Waiting for database to be ready...'
        until php bin/console doctrine:query:sql 'SELECT 1' > /dev/null 2>&1; do
          echo 'Database not ready yet, waiting...'
          sleep 2
        done
        echo 'Database is ready, clearing cache...'
        php bin/console cache:clear --no-warmup
        echo 'Installing assets...'
        php bin/console assets:install public --symlink --relative
        echo 'Running migrations...'
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        echo 'Migrations completed successfully!'
        echo 'Setting up permissions...'
        mkdir -p /app/var/log /app/var/cache /app/public/uploads
        chown -R www-data:www-data /app/var /app/public/uploads
        chmod -R 775 /app/var /app/public/uploads
        echo 'Starting production server...'
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - pteroca

volumes:
  pteroca_database:
  pteroca_app_var:
  pteroca_app_uploads:

networks:
  pteroca:
    driver: bridge
