# Mosquitto MQTT Broker Configuration
# This is a basic configuration file for the Mosquitto MQTT broker.
# For more advanced configurations, refer to the official documentation:
# https://github.com/eclipse-mosquitto/mosquitto/blob/master/mosquitto.conf

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

listener 1883
## Authentication ##
allow_anonymous false
# password_file /mosquitto/config/mosquitto.passwd